env:
  node: true
  es6: true
  mocha: true
  es2020: true

plugins:
  - haraka

extends:
  - eslint:recommended
  - plugin:haraka/recommended

root: true

rules:
  no-var: warn
  space-before-function-paren: warn
  no-shadow: warn
  dot-notation: warn
  indent: warn

globals:
  OK: true
  CONT: true
  DENY: true
  DENYSOFT: true
  DENYDISCONNECT: true
  DENYSOFTDISCONNECT: true
